name: nhom11_giaodien
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9 
  timeline_tile: ^2.0.0
  provider: ^6.0.5
  image_picker: ^1.0.0
  fl_chart: ^0.68.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  permission_handler: ^11.2.0
  intl: ^0.20.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  firebase_database: ^11.3.5
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  shared_preferences: ^2.3.3
  easy_localization: ^3.0.7
  flutter_animate: ^4.5.0
  speech_to_text: ^7.0.0
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/sounds/
